format_version: 10
pipelines:
  pipeline-test:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-392ee3b:
        git: https://github.com/scottholmesendava/gocd_learning.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                command: echo
                run_if: passed
